# ansible-playbook apt-install-dotnet-core.yml
# Chris Joakim, Microsoft, 2020/02/27
# See https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1604

---
- hosts: dsvmall
  remote_user: cjoakim

  tasks:

  - name: sudo apt-get update
    shell: sudo /usr/bin/apt-get update
    args:
      chdir: /home/cjoakim/

  - name: sudo apt-get install apt-transport-https
    shell: sudo /usr/bin/apt-get install apt-transport-https
    args:
      chdir: /home/cjoakim/

  - name: sudo apt-get update
    shell: sudo /usr/bin/apt-get update
    args:
      chdir: /home/cjoakim/

  - name: sudo apt-get install dotnet-sdk-3.1
    shell: sudo /usr/bin/apt-get -y install dotnet-sdk-3.1
    args:
      chdir: /home/cjoakim/

  - name: dotnet --version
    shell: dotnet --version
    args:
      chdir: /home/cjoakim/
