# ansible-playbook git-pull.yml
# Chris Joakim, Microsoft, 2020/02/27

---
- hosts: dsvmall
  remote_user: cjoakim

  tasks:

  - name: git reset --hard
    shell: /usr/bin/git reset --hard
    args:
      chdir: /home/cjoakim/github/azure-dsvm-private

  - name: git pull
    shell: /usr/bin/git pull
    args:
      chdir: /home/cjoakim/github/azure-dsvm-private
