# ansible-playbook git-pull.yml
# Chris Joakim, Microsoft, 2020/03/11

---
- hosts: dsvmall
  remote_user: cjoakim

  tasks:

  - name: git reset --hard
    shell: /usr/bin/git reset --hard
    args:
      chdir: /home/cjoakim/azure-ansible

  - name: git pull
    shell: /usr/bin/git pull
    args:
      chdir: /home/cjoakim/azure-ansible
