# ansible-playbook git-setup.yml
# git config --list
# Chris Joakim, Microsoft, 2020/03/11

---
- hosts: dsvmall
  remote_user: cjoakim

  tasks:
  - name: git config user.name
    git_config:
      name: user.name
      scope: global
      value: 'Chris Joakim'

  - name: git config user.email
    git_config:
      name: user.email
      scope: global
      value: 'christopher.joakim@gmail.com'

  - name: git config list global
    git_config:
      list_all: yes
      scope: global

  - name: remove the azure-ansible repo if present
    shell: rm -rf azure-ansible/
    args:
      chdir: /home/cjoakim/

  - name: clone azure-ansible repo
    shell: git clone https://github.com/cjoakim/azure-ansible.git
    args:
      chdir: /home/cjoakim/

# - name: clone azure-xxxx-yyyy repo
#   shell: git clone git@github.com:cjoakim/azure-xxxx-yyyy.git
#   args:
#     chdir: /home/cjoakim/
