# ansible-playbook redeploy-webapp.yml
# dsvm-all dsvm-use dsvm-weu dsvm-cin dsvm-jpe
# Chris Joakim, Microsoft, 2018/06/10

---
- hosts: dsvm-all
  remote_user: cjoakim

  tasks:

  - name: git reset --hard (core config repo)
    shell: /usr/bin/git reset --hard
    args:
      chdir: /home/cjoakim/github/azure

  - name: git pull (core config repi)
    shell: /usr/bin/git pull
    args:
      chdir: /home/cjoakim/github/azure

  - name: git reset --hard (web app)
    shell: /usr/bin/git reset --hard
    args:
      chdir: /home/cjoakim/github/azure-around-the-world

  - name: git pull (web app)
    shell: /usr/bin/git pull
    args:
      chdir: /home/cjoakim/github/azure-around-the-world

  - name: .bash_profile
    shell: cp /home/cjoakim/github/azure/dsvm/profile/bash_profile /home/cjoakim/.bash_profile

  - name: npm install
    shell: /usr/bin/npm install
    args:
      chdir: /home/cjoakim/github/azure-around-the-world

  - name: gen hostinfo.json
    shell: /usr/bin/nodejs main.js gen_hostinfo_file
    args:
      chdir: /home/cjoakim/github/azure-around-the-world
